{% set name = "prql-compiler" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prql/prql/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2b2f64d5173800b1b82b1644e54b9c5e47e571d93faa1962371e52a47361dbb6

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - prqlc --help

about:
  home: https://prql-lang.org
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Simple, powerful, pipelined SQL replacement
  dev_url: https://github.com/prql/prql

extra:
  recipe-maintainers:
    - danielnachun
