context:
  version: "0.13.3"

package:
  name: prql-compiler
  version: ${{ version }}

source:
  url: https://github.com/prql/prql/archive/${{ version }}.tar.gz
  sha256: f64c22933ba0d4f5664bacbd2278de41baf74cef3a20e86b718dbd6348fc369f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - prqlc --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Simple, powerful, pipelined SQL replacement
  homepage: https://prql-lang.org
  repository: https://github.com/prql/prql

extra:
  recipe-maintainers:
    - danielnachun
