context:
  version: "0.13.8"

package:
  name: prql-compiler
  version: ${{ version }}

source:
  url: https://github.com/prql/prql/archive/${{ version }}.tar.gz
  sha256: 68fb0ee26239de7b63da3af60a63f01dee290b433e52a2805d28735700ad6b3d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - prqlc --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Simple, powerful, pipelined SQL replacement
  homepage: https://prql-lang.org
  repository: https://github.com/prql/prql

extra:
  recipe-maintainers:
    - danielnachun
