context:
  version: "0.13.9"

package:
  name: prql-compiler
  version: ${{ version }}

source:
  url: https://github.com/prql/prql/archive/${{ version }}.tar.gz
  sha256: a425c507dffc36d1e6a0d0fce1f7352dee47d818b90d3463e0d3f30963d86989

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - prqlc --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Simple, powerful, pipelined SQL replacement
  homepage: https://prql-lang.org
  repository: https://github.com/prql/prql

extra:
  recipe-maintainers:
    - danielnachun
